services:
  web:
    build: .
    image: apache-php7
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
    container_name: web
  db:
    hostname: mysql
    image: mysql:5.7.36
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    platform: linux/x86_64 # Necessary for running on Apple silicon
    container_name: db
